pipeline{
    agent any

    environment {
        //registry = "109669590912.dkr.ecr.us-east-1.amazonaws.com/dev-ecr"
        registry = "737349677596.dkr.ecr.us-east-1.amazonaws.com/frontend/web-app"
    }

    stages{
        stage("Review Directory"){
            steps{
                sh '''ls -ltr
                        cd front-app-k8s
                        npm --version
                        node --version
                      '''
            }
        }
        stage("Install"){
            steps{
                sh '''
                    cd front-app-k8s
                    npm install
                      '''
            }
        }
        stage("Build"){
            steps{
                sh '''
                    cd front-app-k8s
                    npm run build
                    '''
            }
        }
        stage("Push Image"){
            steps{
                sh'''
                    cd front-app-k8s
                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $registry
                    docker build -t dev-ecr .
                    docker tag dev-ecr:latest $registry:latest
                    docker push $registry:latest
                '''
            }
        }
        stage("Deploy in EKS"){
            steps{
                sh'''
                    cd front-app-k8s
                    aws eks update-kubeconfig --region us-east-1 --name dev-eks
                    kubectl get nodes
                    kubectl apply -f front.yaml
                    kubectl delete -f deployment.yml
                    kubectl apply -f deployment.yml
                '''
            }
        }
    }
}
