name: 'Deploy Terraform on AWS'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::109669590912:role/DevOpsRole
        aws-region: us-east-1
        
    - name: Terraform Plan
      run: make plan
      working-directory: ./aws_eks_terraform
